import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dcd9da',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#591d00',
        background: '#fbf9fa',
        'tertiary-fixed': '#fbdebe',
        'on-secondary': '#ffffff',
        'tertiary-container': '#362611',
        'surface-variant': '#e4e2e3',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#7d2d00',
        'on-tertiary-container': '#a48c70',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'on-primary-container': '#8591a2',
        surface: '#fbf9fa',
        'inverse-surface': '#303031',
        'on-secondary-fixed': '#360f00',
        'surface-container-low': '#f5f3f4',
        'on-surface-variant': '#44474c',
        'on-tertiary-fixed': '#271905',
        'surface-container-high': '#eae7e9',
        'on-tertiary': '#ffffff',
        'surface-container': '#f0edee',
        'inverse-on-surface': '#f3f0f1',
        secondary: '#a43d00',
        'inverse-primary': '#bbc7da',
        'on-background': '#1b1b1d',
        'on-tertiary-fixed-variant': '#56432c',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'outline-variant': '#c4c6cc',
        outline: '#75777c',
        tertiary: '#1f1202',
        'secondary-fixed': '#ffdbcd',
        'on-surface': '#1b1b1d',
        'secondary-fixed-dim': '#ffb597',
        'surface-tint': '#535f6f',
        'on-primary-fixed-variant': '#3c4857',
        'secondary-container': '#fd6c22',
        'primary-fixed': '#d7e3f6',
        'surface-bright': '#fbf9fa',
        'tertiary-fixed-dim': '#ddc2a3',
        'primary-fixed-dim': '#bbc7da',
        'on-primary-fixed': '#101c2a',
        primary: '#091523',
        'surface-container-highest': '#e4e2e3',
        'primary-container': '#1e2a38',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        xxl: '80px',
        sm: '8px',
        md: '16px',
        xs: '4px',
        xl: '48px',
      },
      fontFamily: {
        'body-md': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        h3: ['Plus Jakarta Sans', 'sans-serif'],
        h1: ['Plus Jakarta Sans', 'sans-serif'],
        h2: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
